### ISSUE TITLE
Implement Snapshot and Recording Upload to GridFS

### ISSUE THREAD

**Issue by mohamdlog** [oss-slu/DroneWorld#111]
**Description:**
Integrate MongoDB's GridFS to store large files such as image snapshots and video recordings. Modify the `save_pic()` and `save_recording()` methods to store these files directly in MongoDB GridFS, rather than saving them locally. Store the file references in the MongoDB reports collection.

**Acceptance Criteria:**
- [ ] Video recordings are stored directly in MongoDB GridFS.
- [ ] Snapshots are stored directly in MongoDB GridFS.
- [ ] File references (e.g., file IDs) are included in the corresponding MongoDB report document.
- [ ] Images can be successfully uploaded, stored, and retrieved from GridFS.
- [ ] Videos can be successfully uploaded, stored, and retrieved from GridFS.

**Reason:**
Using GridFS ensures that large files like images and video recordings can be efficiently stored within MongoDB without size limitations. This also keeps the application scalable, avoiding the need for external file systems.

**Comment by nguzinski** [comment]
I'm going to set up what I have currently for you to take a look, I have a few confusions, 1. in what format are these picture/recording objects being passed, I'm unsure if I am to go to a file location or if they are picture/recording objects , 2. I'm unsure the naming scheme requested, as it just wants fileID's, if I knew the data type being passed I could know if I am able to pull an ID from it, or if instead I am to make a numbering system.
what I push should hopefully work, but again I'm restricted by not knowing the use case specifics.
further I'll have to test tomorrow on my windows machine, which is able to use the unreal engine

**Comment by mohamdlog** [comment]
The pictures and recordings are likely passed as either binary data (e.g., image or video files) or file paths. To handle them with MongoDB’s GridFS, first determine whether the data is binary or file paths using debug prints. If it’s binary, you can directly upload it to GridFS and store the returned file ID in MongoDB. If it’s a file path, you need to open the file, read it as binary, and then upload it to GridFS. You don’t need to create a naming scheme; GridFS will generate a unique file ID, which can be saved with the report metadata for future retrieval.

**Comment by nguzinski** [comment]
Added the checking for both uploading and downloading to fit binary and filepath, should work well now.
