### ISSUE TITLE
Fix Violation Detected in Report

### ISSUE THREAD

**Issue by mohamdlog** [oss-slu/DroneWorld#145]
**Description:**
A violation has been detected in the reports (see attached screenshot). The report displays a warning but lacks further details. Please investigate the cause of this violation and work towards resolving it. Since it's currently  fall break, if the solution requires a more extensive fix, making acceptable progress towards it is sufficient for now. Please do not feel any pressure, and enjoy your break.

![Screenshot 2024-10-22 124151](https://github.com/user-attachments/assets/fdbfe4d5-d71a-4edb-beb1-f5aed1288d99)

**Acceptance Criteria:**
- [x] The cause of the violation is identified.
- [x] The issue is resolved or progress has been made towards a solution if a larger fix is needed.

**Reason:**
The report currently shows an unclear violation warning. Fixing this will improve the accuracy of the system and user experience by ensuring that violations are only shown when necessary and include relevant information.

**Good Files to Look at for More Information:**
`Droneworld\backend\PythonClient\server\simulation_server.py`
`DroneWorld\frontend\src\components\Dashboard.jsx`
`DroneWorld\frontend\src\components\FuzzyDashboard.jsx`

**Comment by nguzinski** [comment]
It seems like I'm going to have to run down a few rabbit holes, to properly alert the user to the error. Currently, it is just one state fail flag, that turns on when a file state errors, or corrupts/ isn't a complete report, however, that information is not useful to the user.
I'll spend some more time digging into it, so that we can get actually decent error messages instead of "things have broken somewhere".

**Comment by nguzinski** [comment]
Its currently using a location state, that is within reacts documentation, instead of our own creation, so it may take a second

**Comment by mohamdlog** [comment]
You're all good, check my most recent comment on your pull request.

**Comment by mohamdlog** [comment]
> Its currently using a location state, that is within reacts documentation, instead of our own creation, so it may take a second. currently, the error is caused when the backend routes a file to the front end, but if anything goes wrong it errors out. I'll have to read the react docs more thoroughly to be able to fix/ rebuild that section. But I know where I am going from here
> 
> 
> 
> there error is shown on the backend, but I have to just route it to the front end, however there are multiple different kinds existing on the backend so it will be a bit of work.

setVoilation (misspelled, should be setViolation) sets the state to indicate a violation when certain files contain a 'FAIL'. This lets the component know a violation has occurred.
