### ISSUE TITLE
Improve Report Dashboard Loading Experience

### ISSUE THREAD

**Issue by mohamdlog** [oss-slu/DroneWorld#160]
**Description:** 
When the report dashboard needs to fetch a large number of reports, the loading time becomes significant. During this period, users are presented with a screen indicating that there are no reports and are prompted to return to the home page. To enhance the user experience, implement a loading UI that allows users to wait while the reports are being retrieved. Additionally, there is an unnecessary loading UI present on the landing page, which should be removed since there is no data to load there.

**Acceptance Criteria**
- [x] A loading indicator is displayed on the report dashboard while reports are being fetched.
- [x] Users are not shown the "No reports found" message until the data fetching process is complete.
- [x] Users are not shown the prompt to return home until the data fetching process is complete.
- [x] The existing loading UI on the landing page is removed.
- [x] The loading experience is smooth and does not cause confusion or frustration for the user.

**Reason:** 
Enhancing the loading experience on the report dashboard will prevent users from encountering misleading "No reports" messages during data retrieval, thereby reducing confusion and frustration. Removing the unnecessary loading UI from the landing page will streamline the user interface, leading to a more intuitive and efficient user experience.

**Comment by Alhajideen** [comment]
This is interesting feature. Can you please assign ticket to me @mohamdlog ?

**Comment by mohamdlog** [comment]
> This is interesting feature. Can you please assign ticket to me @mohamdlog ?

Of course, thank you for your interest.
