### ISSUE TITLE
Fuzzy testing: Fuzz time of day

### ISSUE THREAD

**Issue by yashaswini-slu** [oss-slu/DroneWorld#20]
When the fuzzy testing toggle is enabled, display more specific type of fuzzy testing.
User will have a option to enable or disable the specific type of testing.

**Comment by yashaswini-slu** [comment]
The types of fuzzy testing are

- Wind
- Time of day
- Initial Postion

**Comment by sr259** [comment]
![image](https://github.com/oss-slu/DroneWorld/assets/93687716/b6c4c5b5-7641-42ef-8744-e5dd70695469)


This is what I had in mind when implementing this. When enabled, the fuzzy tester would have three check boxes that appear. Whether or not these are marked would enable the fuzzy test for each type.

**Comment by sr259** [comment]
I had some questions regarding the types. Is the wind type for the Fuzzy test referencing the wind speed? Also, would you want me to disable any choices where if a checkbox is clicked, the corresponding user input would be disabled, similar to how the fuzzy test was done previously? If so, how would this work with wind shear and turbulent wind?

**Comment by ankyAgrawal** [comment]
This is a great question @sr259 . I think the UI will explode with so me checkboxes/switches appearing at random places. I feel it would be a good idea to develop a separate screen / wizard step for fuzzing various simulation params. Perhaps, wizard step 4 could be Fuzz Test Configuration where you could list all params and show a checkbox next to them.

**Comment by sr259** [comment]
Yes, that can work. It does seem to start getting too crowded but for now, it seems somewhat coherent. I implemented the checkboxes and everything and they fit snugly in the UI. I definitely think that having a wizard set up for fuzzing various simulation parameters would be a good idea for streamlining the process, at least once we have more information on the specifics of the fuzzy testing.

**Comment by sr259** [comment]
![image](https://github.com/oss-slu/DroneWorld/assets/93687716/e2ae9818-647c-4c29-b076-66bd890f6ea3)

@ankyAgrawal Here is the Implementation of the fuzzy test for the time being. It is impossible to unclick all three boxes, one will be on at all times.
