### ISSUE TITLE
UI - Torque Battery Test Property

### ISSUE THREAD

**Issue by yashaswini-slu** [oss-slu/DroneWorld#21]
As a Drone Tester
I want to input battery details for my drone
So that the simulator can track my battery details

**Comment by yashaswini-slu** [comment]
Requirements

- input a current battery capacity as % (0-100)

**Comment by yashaswini-slu** [comment]
Add the torque battery details in the JSON with these parameters - 
       torque_battery_monitor:{
            enable:false,
            param:[1]
        }

**Comment by mohamdlog** [comment]
**Sub-issues:**
- [ ] https://github.com/oss-slu/DroneWorld/issues/100
