### ISSUE TITLE
UI - Magnetometer details

### ISSUE THREAD

**Issue by yashaswini-slu** [oss-slu/DroneWorld#23]
As a Drone Tester
I want to input Magnetometer specific details for my drone
So that the simulator can add Magnetometer specific details

**Comment by yashaswini-slu** [comment]
Requirements 

-  NoiseSigma
-  ScaleFactor
-  NoiseBias,
-  UpdateLatency
-  UpdateFrequency
-  StartupDelay

**Comment by yashaswini-slu** [comment]
Default Value

 "NoiseSigma": 0.005,
        "ScaleFactor": 1,
        "NoiseBias": 0,
        "UpdateLatency": 0,
        "UpdateFrequency": 50,
        "StartupDelay": 0

**Comment by hebronh** [comment]
//
