### ISSUE TITLE
API Integration for GPS

### ISSUE THREAD

**Issue by yashaswini-slu** [oss-slu/DroneWorld#43]
As a Drone Tester
I want to input GPS specific details for my drone
So that the simulator can add GPS specific details

Feild Values

"EphTimeConstant": 0.9,
"EpvTimeConstant": 0.9,
"EphInitial": 25,
"EpvInitial": 25,
"EphFinal": 0.1,
"EpvFinal": 0.1,
"EphMin3d": 3,
"EphMin2d": 4,
"UpdateLatency": 0.2,
"UpdateFrequency": 50,
"StartupDelay": 1

**Comment by kalyus** [comment]
simulation task manager.py
