### ISSUE TITLE
React app crashes when attempting to re-enter the time of day after erasing it

### ISSUE THREAD

**Issue by mohamdlog** [oss-slu/DroneWorld#99]
**Description:** In the `Environmental Configuration` section of the React App, erasing the `Time of Day` crashes the app and displays errors.

**Tasks:**
1. Investigate and identify the root cause of the crash when the `Time of Day` field is erased.
2. Implement a fix to prevent the app from crashing when the field is cleared.
3. Test the fix across different scenarios to ensure the issue is fully resolved.

**Reason for Update:**  The app currently crashes when the `Time of Day` field is cleared, which disrupts the user experience and prevents users from successfully configuring the environment.

**Acceptance Criteria:**
- The app no longer crashes when the `Time of Day field` is erased.
- Appropriate error handling is in place to manage invalid input.

**Additional Notes:**
Ensure that any changes made do not introduce new issues in other parts of the `Environmental Configuration` section.

**Comment by nguzinski** [comment]
fixed the issue, used the dayjs library which handles null values, when expecting a Hour minute second format, issue was cause due to using val.,val.,val., which when the colons in 10:00:00 where deleted, this would be a null value and thus lead to the crash
